# s=set()
# n=input("Enter number: ")
# s.add(int(n))
# n=input("Enter number: ")
# s.add(int(n))
# n=input("Enter number: ")
# s.add(int(n))
# n=input("Enter number: ")
# s.add(int(n))
# n=input("Enter number: ")
# s.add(int(n))
# n=input("Enter number: ")
# s.add(int(n))
# n=input("Enter number: ")
# s.add(int(n))
# n=input("Enter number: ")
# s.add(int(n))

# print(s)

s = set()

n = input("Enter number: ")
s.add(int(n))
n = input("Enter number: ")
s.add(int(n))
n = input("Enter number: ")
s.add(int(n))
n = input("Enter number: ")
s.add(int(n))
n = input("Enter number: ")
s.add(int(n))
n = input("Enter number: ")
s.add(int(n))
n = input("Enter number: ")
s.add(int(n))
n = input("Enter number: ")
s.add(int(n))

print(s)